version: '3'

services:

  simple_collector:
    build: .
    image: simple_collector:latest
    volumes:
      - /tmp/simple_collector:/source
      - /tmp/simple_collector:/output:rw
    environment:
      SOURCE_FILE: /source/source.txt
      OUTPUT_FILE: /output/output.txt
      OUTPUT_FILE_TYPE: txt
      WORKERS_COUNT: 1000
      TIMEOUT: 60
      LOG_LEVEL: 5